# Generated by Django 5.1.6 on 2025-02-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True, verbose_name='date and time')),
                ('author', models.CharField(max_length=100)),
                ('assistance_type', models.CharField(max_length=100, verbose_name='assistance type')),
                ('geolocation', models.CharField(blank=True, help_text='Enter X, Y coordinates', max_length=100, null=True)),
                ('location_details', models.TextField(blank=True, null=True, verbose_name='location details')),
                ('extended_assistance', models.BooleanField(default=False, verbose_name='follow-up needed')),
                ('notes', models.TextField(blank=True, help_text='Additional details or observations about the assistance provided', null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'assistance',
                'verbose_name_plural': 'assistances',
                'ordering': ('date_time',),
            },
        ),
    ]
