# Generated by Django 5.1.6 on 2025-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0002_alter_assistance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='location_details',
        ),
        migrations.AddField(
            model_name='assistance',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='assistance address'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='address_reference',
            field=models.TextField(blank=True, null=True, verbose_name='assistance address reference'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='extended_assistance_details',
            field=models.TextField(blank=True, null=True, verbose_name='follow-up details'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='geolocation',
            field=models.CharField(blank=True, help_text='Enter X, Y coordinates', max_length=100, null=True, verbose_name='geolocation'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional details or observations about the assistance provided', null=True, verbose_name='notes'),
        ),
    ]
