# Generated by Django 5.1.6 on 2025-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0003_remove_assistance_location_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='address_reference',
            field=models.TextField(blank=True, null=True, verbose_name='address reference'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
    ]
