# Generated by Django 5.1.6 on 2025-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0004_assistance_updated_at_alter_assistance_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='is_first_assistance',
            field=models.BooleanField(default=False, verbose_name='is first assistance'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.TextField(blank=True, null=True, verbose_name='assistance type'),
        ),
    ]
