# Generated by Django 5.1.6 on 2025-04-04 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('purpose', models.CharField(max_length=200, verbose_name='purpose')),
                ('cuit', models.CharField(help_text='Formato: XX-XXXXXXXX-X o XXXXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CUIT debe tener formato XX-XXXXXXXX-X o 11 dígitos sin guiones', regex='^(\\d{2}-\\d{8}-\\d{1}|\\d{11})$')], verbose_name='CUIT')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('geolocation', models.CharField(blank=True, help_text='Enter X, Y coordinates', max_length=100, null=True, verbose_name='geolocation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('name',),
            },
        ),
    ]
