# Generated by Django 5.1.6 on 2025-02-19 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='DNI must be an 8-digit number', regex='^\\d{8}$')], verbose_name='dni')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='XXX-XXX-XXXX', max_length=100, null=True, verbose_name='phone')),
                ('reference_phone_number', models.CharField(blank=True, help_text='XXX-XXX-XXXX', max_length=100, null=True, verbose_name='reference phone')),
                ('location', models.TextField(blank=True, help_text='Enter the approximate location where the person was found (e.g., street name, nearby landmark, or intersection)', null=True)),
                ('is_fixed_or_transitory_place', models.BooleanField(default=False, verbose_name='transitory location')),
                ('contact_info', models.TextField(blank=True, help_text='Enter any contact details related to this person (e.g., phone number, email, or social media)', null=True, verbose_name='contact info')),
                ('life_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='life center')),
                ('receives_subsidies', models.BooleanField(help_text='Does this person receives any subsidies or financial aid - Y/N', verbose_name='subsidies')),
                ('subsidies_details', models.TextField(blank=True, default=False, help_text='Name the subsidies this person receives', null=True, verbose_name='subsidies description')),
            ],
            options={
                'verbose_name': 'beneficiary',
                'verbose_name_plural': 'beneficiaries',
                'ordering': ('name',),
            },
        ),
    ]
