# Generated by Django 5.1.6 on 2025-02-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='location',
            field=models.TextField(blank=True, help_text='Enter the approximate location where this person was found (e.g., street name, nearby landmark, or intersection)', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(blank=True, help_text='format: XXX-XXX-XXXX', max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='receives_subsidies',
            field=models.BooleanField(default=False, help_text='Does this person receives any subsidies or financial aid - Y/N', verbose_name='subsidies'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reference_phone_number',
            field=models.CharField(blank=True, help_text='format: XXX-XXX-XXXX', max_length=100, null=True, verbose_name='reference phone'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='subsidies_details',
            field=models.TextField(blank=True, help_text='Name all the subsidies this person receives', null=True, verbose_name='subsidies description'),
        ),
    ]
