# Generated by Django 5.1.6 on 2025-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>', null=True),
        ),
    ]
