# Generated by Django 5.1.6 on 2025-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Enter any contact details related to this person (e.g., email, or social media)', null=True, verbose_name='contact info'),
        ),
    ]
