# Generated by Django 5.1.6 on 2025-04-04 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_alter_beneficiary_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='health_info',
            field=models.TextField(blank=True, help_text='Describe any relevant health conditions, ongoing treatments, or recurring needs such as medication, psychological support, or mobility aids. This field is intended for background health information rather than specific assistances provided.', null=True, verbose_name='health info'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>', null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='DNI must be between 6 and 10 digits', regex='^\\d{6,10}$')], verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='location',
            field=models.TextField(blank=True, help_text='Enter the approximate location where this person was found (e.g., street name, nearby landmark, or intersection)', null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='surname'),
        ),
    ]
