# Generated by Django 5.1.6 on 2025-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0005_beneficiary_health_info_alter_beneficiary_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ('first_name',), 'verbose_name': 'beneficiary', 'verbose_name_plural': 'beneficiaries'},
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='surname',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
    ]
