# Generated by Django 5.1.6 on 2025-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0006_alter_beneficiary_options_remove_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='location',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='receives_subsidies',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='subsidies_details',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='address_reference',
            field=models.TextField(blank=True, null=True, verbose_name='address reference'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='geolocation',
            field=models.CharField(blank=True, help_text='Enter X, Y coordinates', max_length=100, null=True, verbose_name='geolocation'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_family_contact',
            field=models.TextField(default=False, help_text='Does this person any relationship or contact with family members? Specify', verbose_name='has family contact'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='has_physical_dni',
            field=models.BooleanField(default=False, verbose_name='has physical dni'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='subsidies',
            field=models.TextField(default=False, help_text='Does this person receives any subsidies or financial aid', verbose_name='subsidies'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reference_phone_number',
            field=models.TextField(blank=True, help_text='Whose number is it?', null=True, verbose_name='reference phone'),
        ),
    ]
