# Generated by Django 5.1.6 on 2025-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0007_remove_beneficiary_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='author',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='author_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='author'),
        ),
    ]
