# Generated by Django 5.1.6 on 2025-06-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0008_beneficiary_author_beneficiary_author_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='has_physical_dni',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='subsidies',
            field=models.TextField(blank=True, help_text='Does this person receive any subsidies or financial aid', null=True, verbose_name='subsidies'),
        ),
    ]
