# Generated by Django 5.1.6 on 2025-06-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0009_remove_beneficiary_has_physical_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='has_physical_dni',
            field=models.BooleanField(default=False, verbose_name='has physical dni'),
        ),
    ]
